Add hook for ShouldShowJesterToTeam
TTT-2/ttt2-role_jes pull request #63
Opened 2023-10-20 15:05 UTC by Spanospy

Adds a TTT2JesterShouldShow hook for other addons to override ShouldShowJesterToTeam's behaviour, for usage in special Traitor or Jester roles.

2023-10-20 18:01 UTC, Spanospy commented
cc @EntranceJew as I know you currently patch this function in one of your addons https://github.com/EntranceJew/gmod-addons/blob/main/ttt2-role_collusionist/lua/terrortown/entities/roles/collusionist/shared.lua#L249-L271

2023-10-22 14:50 UTC, TimGoll requested changes
please add these new lines, otherwise it is fine

2023-10-22 14:50 UTC, TimGoll commented on lua/terrortown/entities/roles/jester/shared.lua
> +		if overrideShow ~= nil then return overrideShow end
```suggestion
		local overrideShow = hook.Run("TTT2JesterShouldShow", ply)

		if overrideShow ~= nil then return overrideShow end

```

2023-10-24 17:18 UTC, TimGoll approved these changes

2023-10-24 17:18 UTC, merged